---
image: registry.cloud.fits/fits/buildtools:dev

merge-request:
  script: 
    - docker-make -x rule2,rule3 --summary --build-only metal-core-merge-request
  only:
    - merge_requests

master:
  script:
    - docker-make -x rule2,rule3 --summary --build-only metal-core
  only:
    - master
