image: registry.cloud.fits/fits/buildtools:1

stages:
- push

latest:
  stage: push
  script:
    - docker-make --Lint --summary --build-arg TAG=latest
  only:
    - master

stable:
  stage: push
  script:
    - docker-make --Lint --summary --build-arg TAG=stable
  only:
    - stable
