version: "2"

services:
  pixiecore:
    image: danderson/pixiecore
    container_name: pixiecore
    command: ["api", "http://localhost:4242", "--dhcp-no-bind"]
    network_mode: host

  metalcore:
    build:
      context: .
    image: registry.fi-ts.io/metal/metalcore
    container_name: metalcore
    network_mode: host
    environment:
      METALCORE_LOG_LEVEL: DEBUG
      METALCORE_SERVER_ADDRESS: localhost
      METALCORE_SERVER_PORT: 4242
      METALCORE_METAL_API_PROTOCOL: http
      METALCORE_METAL_API_ADDRESS: localhost
      METALCORE_METAL_API_PORT: 8090

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    network_mode: host
    environment:
      PORT: 9090
      API_URL: http://localhost:8090/apidocs.json

  metal-api:
    image: registry.fi-ts.io/metal/metal-api
    container_name: metal-api
    tty: true
    network_mode: host
    environment:
      METAL_API_WITH_MOCK_DATA: "true"
      METAL_API_BIND_ADDR: localhost
    command: ["/metal-api", "--port", "8090"]

  discover:
    image: registry.fi-ts.io/metal/discover
    container_name: discover
    network_mode: host
    depends_on:
      - pixiecore
      - metalcore
      - swagger
      - metal-api
    environment:
      DISCOVER_REPORTURL: http://localhost:4242/device/register/1234-1234-1234
