version: '3.5'

services:
  metal-core:
    build:
      context: .
    image: registry.fi-ts.io/metal/metal-core

  metal-core-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: registry.fi-ts.io/metal/metal-core
