version: '2'

services:
  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    network_mode: host

  pixiecore:
    image: danderson/pixiecore
    container_name: pixiecore
    command: ["api", "http://localhost:4242", "--dhcp-no-bind"]
    network_mode: host

  metal-core:
    build:
      context: .
    image: registry.fi-ts.io/metal/metal-core
    container_name: metal-core
    network_mode: host
    environment:
      METAL_CORE_CONTROL_PLANE_IP: localhost
      METAL_CORE_FACILITY_ID: FRA
      METAL_CORE_LOG_LEVEL: DEBUG
      METAL_CORE_METAL_API_PORT: 8090
      METAL_CORE_HAMMER_IMAGE_PREFIX: metal-hammer

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    network_mode: host
    environment:
      PORT: 9090
      API_URL: http://localhost:8090/apidocs.json

  metal-api:
    build:
      context: ../maas-service
    image: registry.fi-ts.io/metal/metal-api
    container_name: metal-api
    tty: true
    network_mode: host
    environment:
      METAL_API_WITH_MOCK_DATA: "true"
      METAL_API_BIND_ADDR: localhost
      METAL_API_DB_ADDR: localhost:28015
    command: >
      /bin/sh -c "
        sleep 1;
        /metal-api --port 8090;
      "

  metal-hammer:
    build:
      context: ../metal-hammer
      dockerfile: ../metal-core/test/e2e/MetalHammer
    image: registry.fi-ts.io/metal/metal-hammer
    container_name: metal-hammer
    network_mode: host
    command: >
      /bin/sh -c "
        sleep 6;
        /metal-hammer;
      "
