version: '3.5'

networks:
  metal:
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}

volumes:
  nsq-data-volume:

services:
  nsqlookupd:
    image: nsqio/nsq:v1.1.0
    container_name: nsqlookupd
    networks:
      - metal
    volumes:
      - nsq-data-volume:/data
    command: /nsqlookupd -log-level error
    ports:
      - "${NSQLOOKUPD_TCP_PORT}"
      - "${NSQLOOKUPD_HTTP_PORT}"

  nsqd:
    image: nsqio/nsq:v1.1.0
    container_name: nsqd
    networks:
      - metal
    command: /nsqd -log-level error --lookupd-tcp-address=nsqlookupd:${NSQLOOKUPD_TCP_PORT}
    depends_on:
      - nsqlookupd
    ports:
      - "${NSQD_TCP_PORT}"
      - "${NSQD_HTTP_PORT}"

  nsqadmin:
    image: nsqio/nsq:v1.1.0
    container_name: nsqadmin
    networks:
      - metal
    command: /nsqadmin -log-level error --lookupd-http-address=nsqlookupd:${NSQLOOKUPD_HTTP_PORT}
    depends_on:
      - nsqlookupd
    ports:
      - "${NSQADMIN_HTTP_PORT}:${NSQADMIN_HTTP_PORT}"

  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    networks:
      - metal
    ports:
      - "10080:8080"
      - "${RETHINKDB_PORT}:${RETHINKDB_PORT}"

  metal-core:
    build:
      context: .
    image: registry.fi-ts.io/metal/metal-core
    container_name: ${METAL_CORE_CONTAINER_NAME}
    networks:
      metal:
        ipv4_address: ${METAL_CORE_IP}
    ports:
      - "${METAL_CORE_PORT}:${METAL_CORE_PORT}"
    environment:
      METAL_CORE_BIND_ADDRESS: 0.0.0.0
      METAL_CORE_IP: ${METAL_CORE_IP}
      METAL_CORE_PORT: ${METAL_CORE_PORT}
      METAL_CORE_MQ_ADDRESS: nsqlookupd:${NSQLOOKUPD_HTTP_PORT}
      METAL_CORE_SITE_ID: FRA
      METAL_CORE_RACK_ID: Vagrant Rack 1
      METAL_CORE_LOG_LEVEL: DEBUG
      METAL_CORE_METAL_API_IP: metal-api
      METAL_CORE_METAL_API_PORT: ${METAL_API_PORT}
      METAL_CORE_HAMMER_IMAGE_PREFIX: metal-hammer

  metal-api:
    build:
      context: ../metal-api
      dockerfile: Dockerfile.dev
    image: registry.fi-ts.io/metal/metal-api
    container_name: metal-api
    networks:
      - metal
    ports:
      - "${METAL_API_PORT}:${METAL_API_PORT}"
    tty: true
    environment:
      METAL_API_BIND_ADDR: 0.0.0.0
      METAL_API_PORT: ${METAL_API_PORT}
      METAL_API_DB_ADDR: rethinkdb:${RETHINKDB_PORT}
      METAL_API_NETBOX_ADDR: netbox-api-proxy:${NETBOX_PORT}
      METAL_API_NSQD_ADDR: nsqlookupd:${NSQLOOKUPD_TCP_PORT}
      METAL_API_NSQD_HTTP_ADDR: nsqlookupd:${NSQLOOKUPD_HTTP_PORT}
      METAL_API_LOG_LEVEL: debug

  metal-core-swagger:
    image: swaggerapi/swagger-ui
    container_name: core-swagger-ui
    networks:
      - metal
    ports:
      - "${CORE_SWAGGER_PORT}:${SWAGGER_PORT}"
    environment:
      API_URL: http://localhost:${METAL_CORE_PORT}/apidocs.json

  metal-api-swagger:
    image: swaggerapi/swagger-ui
    container_name: api-swagger-ui
    networks:
      - metal
    ports:
      - "${API_SWAGGER_PORT}:${SWAGGER_PORT}"
    environment:
      API_URL: http://localhost:${METAL_API_PORT}/apidocs.json
