FROM alpine:3.8
LABEL maintainer FI-TS Devops <devops@f-i-ts.de>

RUN apk update \
 && apk add \
    ca-certificates \
    ipmitool \
    libpcap-dev

COPY bin/metal-core /

ENTRYPOINT ["/metal-core"]
