version: "2"

services:
  pixiecore:
    image: danderson/pixiecore
    container_name: pixiecore
    command: ["api", "http://10.10.10.10:4242"]
    volumes:
      - ./images:/images
    networks:
      metalcore:
        ipv4_address: 10.10.10.2

  metalcore:
    build: .
    image: metalcore
    container_name: metalcore
    ports:
      - "4242:4242"
    depends_on:
      - pixiecore
    networks:
      metalcore:
        ipv4_address: 10.10.10.10

networks:
  metalcore:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
