version: "2"

services:
  pixiecore:
    image: danderson/pixiecore
    container_name: pixiecore
    command: ["api", "http://localhost:4242", "--dhcp-no-bind"]
    volumes:
      - ./images:/images
    network_mode: host

  metalcore:
    build: .
    image: metalcore
    container_name: metalcore
    ports:
      - "4242:4242"
    depends_on:
      - pixiecore
    network_mode: host
    environment:
      - METALCORE_LOG_LEVEL=DEBUG
      - METALCORE_SERVER_PORT=4242
