package redis

import (
	"context"
	"fmt"
	"net/netip"
	"slices"
	"strings"

	"github.com/metal-stack/metal-core/cmd/internal/switcher/types"
)

const (
	// bootACLTablePrefix is the name prefix of the ACL tables bound to ports in the boot VRF.
	// The tables and their rules are generated by sonic-configdb-utils (boot_acl), metal-core only maintains their port binding.
	bootACLTablePrefix = "BOOT_"
)

// configureBootPort makes the port a routed interface in the boot VRF with its own boot prefix.
func (a *Applier) configureBootPort(ctx context.Context, interfaceName string, adminStatus types.PortStatus, vrfName string, prefix netip.Prefix) error {
	// remove VLAN membership before making the port a routed interface
	err := a.ensureNotBridged(ctx, interfaceName)
	if err != nil {
		return err
	}

	err = a.ensureInterfaceIsVrfMember(ctx, interfaceName, vrfName)
	if err != nil {
		return err
	}

	if err := a.ensurePortConfiguration(ctx, interfaceName, "9000", adminStatus); err != nil {
		return fmt.Errorf("failed to update Port info for interface %s: %w", interfaceName, err)
	}

	if err := a.ensureLinkLocalOnlyIsEnabled(ctx, interfaceName); err != nil {
		return err
	}

	// The switch always uses ::1 within the boot prefix.
	address := netip.PrefixFrom(prefix.Masked().Addr().Next(), prefix.Bits()).String()
	return a.ensureInterfaceAddresses(ctx, interfaceName, []string{address})
}

// ensureInterfaceAddresses configures exactly the given addresses on the interface.
func (a *Applier) ensureInterfaceAddresses(ctx context.Context, interfaceName string, addresses []string) error {
	current, err := a.db.Config.GetInterfaceAddresses(ctx, interfaceName)
	if err != nil {
		return fmt.Errorf("could not retrieve addresses of interface %s: %w", interfaceName, err)
	}

	for _, address := range current {
		if slices.Contains(addresses, address) {
			continue
		}
		a.log.Info("remove address from interface", "name", interfaceName, "address", address)
		if err := a.db.Config.DeleteInterfaceAddress(ctx, interfaceName, address); err != nil {
			return fmt.Errorf("could not remove address %s from interface %s: %w", address, interfaceName, err)
		}
	}

	for _, address := range addresses {
		if slices.Contains(current, address) {
			continue
		}
		a.log.Info("add address to interface", "name", interfaceName, "address", address)
		if err := a.db.Config.SetInterfaceAddress(ctx, interfaceName, address); err != nil {
			return fmt.Errorf("could not add address %s to interface %s: %w", address, interfaceName, err)
		}
	}

	return nil
}

// ensureBootACLBinding binds all boot ACL tables to exactly the given ports.
//
// If required is true, at least one boot acl table must exist, because otherwise booting machines would be unfiltered.
func (a *Applier) ensureBootACLBinding(ctx context.Context, ports []string, required bool) error {
	tables, err := a.bootACLTables(ctx)
	if err != nil {
		return err
	}
	if len(tables) == 0 {
		if required {
			return fmt.Errorf("no acl tables with prefix %s found in CONFIG_DB, generate them with the boot_acl setting of sonic-configdb-utils", bootACLTablePrefix)
		}
		return nil
	}

	desired := slices.Clone(ports)
	slices.Sort(desired)
	desired = slices.Compact(desired)

	for _, table := range tables {
		current, err := a.db.Config.GetACLTablePorts(ctx, table)
		if err != nil {
			return fmt.Errorf("could not retrieve ports of acl table %s: %w", table, err)
		}
		if slices.Equal(current, desired) {
			continue
		}
		a.log.Info("bind acl table to ports", "table", table, "ports", desired)
		if err := a.db.Config.SetACLTablePorts(ctx, table, desired); err != nil {
			return fmt.Errorf("could not bind acl table %s to ports %v: %w", table, desired, err)
		}
	}

	return nil
}

// bootACLBoundPorts returns the union of the ports currently bound to any boot ACL table.
func (a *Applier) bootACLBoundPorts(ctx context.Context) ([]string, error) {
	tables, err := a.bootACLTables(ctx)
	if err != nil {
		return nil, err
	}

	var bound []string
	for _, table := range tables {
		ports, err := a.db.Config.GetACLTablePorts(ctx, table)
		if err != nil {
			return nil, fmt.Errorf("could not retrieve ports of acl table %s: %w", table, err)
		}
		bound = union(bound, ports)
	}
	return bound, nil
}

func union(a, b []string) []string {
	result := slices.Clone(a)
	for _, item := range b {
		if !slices.Contains(result, item) {
			result = append(result, item)
		}
	}
	slices.Sort(result)
	return result
}

func (a *Applier) bootACLTables(ctx context.Context) ([]string, error) {
	tables, err := a.db.Config.GetACLTables(ctx)
	if err != nil {
		return nil, fmt.Errorf("could not retrieve acl tables: %w", err)
	}

	bootTables := make([]string, 0, len(tables))
	for _, table := range tables {
		if strings.HasPrefix(table, bootACLTablePrefix) {
			bootTables = append(bootTables, table)
		}
	}
	return bootTables, nil
}
