name: Build image from release tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -t metalstack/metal-core:${GITHUB_REF##*/} .
        docker push metalstack/metal-core:${GITHUB_REF##*/}
